### PR TITLE
Add test time for expiration checks

### PR DESCRIPTION
**Pull request by jarekratajski**
This is a solution I propose for issue #12

### CODE REVIEW

**Comment by jarekratajski** [comment]
JWTDecoder has now  additional param (optional) Clock  - which is JDK provided class that allows to 
have "non standard time". It is often used in test *see fixedClock.

One can create own subclass of Clock which has some leeway to a default system clock.

**Comment by robotdan** [comment]
If we just want to allow for some clock skew, the simplest way to do this I think would be just update the JWT object. 

For example, this would allow for 30 seconds of clock skew. 


```
    @JsonIgnore
    public boolean isExpired() {
      return expiration != null && expiration.isBefore(ZonedDateTime.now(ZoneOffset.UTC).minusSeconds(30));
    }
```

The only downside here is that it is not configurable.  So we could either hard code it, or allow for skew

```
  @JsonIgnore
  public boolean isExpired(int allowedClockSkewInSeconds) {
    return expiration != null && expiration.isBefore(ZonedDateTime.now(ZoneOffset.UTC).minusSeconds(allowedClockSkewInSeconds));
  }
```

Do we need the `Clock` object, the measurements should all be done in UTC, so I wouldn't think we would have any use for an instant adjusted to a local time zone.

**Comment by jarekratajski** [comment]
The problem is in fact use of:
`ZonedDateTime.now(ZoneOffset.UTC)`

Using ZonedDateTime.now blocks any reasonable testing of code using it. Hence the use of Clock which is standard method of passing configurable time  using for instance `Clock.fixed()`.

**Comment by robotdan** [comment]
Ok, so this is primarily for testing purposes?

**Comment by robotdan** [comment]
Here is kind of what I was thinking, what do you think? 
https://github.com/FusionAuth/fusionauth-jwt/commit/e1adc64fac959d5f230af28b80a7c050e9b59b7c

**Comment by jarekratajski** [comment]
Actually my only problem was testing.  Not a "delay". I needed to do a change, and I saw thataccidentally I can fix  existing issue. So - sorry for a little mess.

Initially I was writing a test like this: 
```
val encodedJWT = expectedEncodedJwt //eyJhbGciOiJIUzI1NiIsInR5cCI6Ikp.... (const token)
val jwt = encoder.decodeJwt(encodedJWT) //my objects that use fusionauth inside
jwt.subject shouldBe "test subject"
```
But I realised I cannot do that because of `ZonedDateTime.now`

**Basically I consider a mistake  any direct use of `ZoneDateTime.now` or any other `.now()` in code. Because such code, when under test, cannot be proven to be 100% repeatable.**

Theoretically, in my test  I can  create anew jwt token each time (I can), and then use it test. If my CI is not incredibly slow it should work. But:
 it can still fail sometimes. Typical case is for instance - I am dubbuging code in tests... and suddenly I do it for too long.

**Comment by robotdan** [comment]
I think I understand what you mean, you'd like to hard code an encoded JWT in your test, and then adjust "now" in your tests to whatever you want it to be to ensure your tests always pass instead of building an encoded JWT for each tests with a real expiration. 

Since this library can easily build a JWT and then encode it, why not just build the JWT dynamically with a valid expiration? This way you can fully control the expiration. 

For example: https://github.com/FusionAuth/fusionauth-jwt/blob/e1adc64fac959d5f230af28b80a7c050e9b59b7c/src/test/java/io/fusionauth/jwt/JWTTest.java#L670

If you really want to control the value of `now()`, I would almost rather sub-class JWTEncoder and override an `expired()` method or something like that so you can isolate this type of code for tests.

**Comment by robotdan** [comment]
Here is another option: https://github.com/FusionAuth/fusionauth-jwt/commit/c7795cc0ab841d93077c405fec2b9c5530d19c9d

Example, you can use whatever strategy you like here since you can just provide your own function to determine if the JWT is expired. 

```java
JWT actual = JWT.getDecoder()
        .withIsExpiredFunction(jwt -> 
           jwt.expiration != null &&
           jwt.expiration.isBefore(ZonedDateTime.now(ZoneOffset.UTC).minusSeconds(61)))
        .decode(encodedJWT, verifier);
```

**Comment by jarekratajski** [comment]
I do like the `nowSupplier`  👍

**Comment by robotdan** [comment]
One final commit. 
https://github.com/FusionAuth/fusionauth-jwt/commit/b91bfacb9f9008dc9d54ee42583628f4d11f5fd1

I renamed it a bit to make it super clear that you are using as non-standard decoder to limit the possibility this code could make it into production. 

Example usage:

```
// Use Jan. 1 2020 UTC
JWT jwt = JWT.getTimeMachineDecoder(ZonedDateTime.of(2020, 1, 1, 0, 0, 0, 0, ZoneOffset.UTC))
     .decode(encodedJWT, verifier);
```
I think I like this ok, will release shortly.

**Comment by robotdan** [comment]
Released version 3.6.0 with this feature.

**Comment by jarekratajski** [comment]
Big thanks for this change. Works great for me.

**Pull request closed without merging**
